# This action does two things:
# 1. It acts as a check to make sure that a PR only affects one set of scripts
# 2. It creates an artifact that we can use to send an immutable link to a DBA so they can download the scripts as a zip

name: dba_artifact

# This action runs when you merge to main or open (or change) a PR into main
on:
  push:
    branches: [ main ]
    paths:
    - 'scripts/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'scripts/**'

jobs:

  # Identify the folder that needs to be packaged into an artifact
  setup:
    runs-on: ubuntu-latest
    outputs:
      create_artifact: ${{ steps.set-dir.outputs.create_artifact }}
      path: ${{ steps.set-dir.outputs.path }}
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40
          
      # NOTE: `since_last_remote_commit: true` is implied by default and falls back to the previous local commit.
      # Find the files that are different so we can identify which package needs to be turned into an artifact

      - id: files
        name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file were changed"
          done   

     # ensure only one subfolder has been changed -- ie. one zip per application
      - id: set-dir
        name: Calculate directories to turn into artifacts
        run: |
          declare -a dirs=()
          for d in scripts/*/ ; do
            if [[ ${{ steps.changed-files.outputs.all_changed_files }} =~ $d ]];
            then
                dirs+=("${d}")
            fi
          done
          if [ ${#dirs[@]} -gt 1 ];
          then
            echo "You may not change more than 1 directory in a single PR. This one has ${#dirs[@]} directories with changes."
            exit 1
          fi
            echo "path::${dirs[0]}" >> $GITHUB_OUTPUT
      
      # Create an artifact that can be accessed as a zip file download
      - uses: actions/upload-artifact@v3.1.3
        if: ${{ success() }}
        with:
          name: "changescripts"
          path: ${{ steps.set-dir.outputs.path }}
          
